### ISSUE TITLE
typings not needed for plunker

### ISSUE THREAD

**Issue by wardbell** [IgorMinar/new-world-test#1]
As discussed today

**Comment by IgorMinar** [comment]
they are not needed but they also don't hurt anything. in plunker you simply don't include the typings and make sure that noEmitOnError is set to false

**Comment by wardbell** [comment]
Yikes.  I don't think we should recommend `noEmitOnError=false`.  That's going to really confuse people - you get no failure information back when systemjs transpiles - and it can be very hard to get all the right d.ts files into a plunker.  

See [this stackoverflow post](http://stackoverflow.com/questions/36128753/no-compilation-error-without-d-ts-files/36143263)

**Comment by IgorMinar** [comment]
But that's what the current plunker does by default.
