### ISSUE TITLE
http://localhost:3000/symbol-observable 404 (Not Found)

### ISSUE THREAD

**Issue by playground** [IgorMinar/new-world-test#13]
Just trying out https://github.com/IgorMinar/new-world-test/tree/master/system-js

Followed the instructions and npm run serve

zone.js:101 GET http://localhost:3000/symbol-observable 404 (Not Found)scheduleTask @ zone.js:101ZoneDelegate.scheduleTask @ zone.js:336Zone.scheduleMacroTask @ zone.js:273(anonymous function) @ zone.js:122send @ VM260:3X @ system.src.js:5031(anonymous function) @ system.src.js:5031ZoneAwarePromise @ zone.js:584(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031(anonymous function) @ system.src.js:5031ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
(index):13 Error: Error: XHR error (404 Not Found) loading http://localhost:3000/symbol-observable(…)(anonymous function) @ (index):13ZoneDelegate.invoke @ zone.js:323Zone.run @ zone.js:216(anonymous function) @ zone.js:571ZoneDelegate.invokeTask @ zone.js:356Zone.runTask @ zone.js:256drainMicroTaskQueue @ zone.js:474ZoneTask.invoke @ zone.js:426
zone.js:101 GET http://localhost:3000/symbol-observable 404 (Not Found)

**Comment by IgorMinar** [comment]
that's likely due to to rxjs beta.7. downgrading to beta.2 should resolve the problem. in the next push we'll support beta.6. beta.7 compatibility will likely happen after ng-conf - we'll see

@robwormald can you confirm?

**Comment by robwormald** [comment]
Yep, that's what it is, beta7 introduced a new dependency.
